version: '3'

services:
  db:
    image: mongo
    container_name: markr-mongoDB
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: VcFYJ_8[BK
    tty: true
    volumes:
      - db-data-dev:/data/db
    ports:
      - "27018:27017"

volumes:
  db-data-dev: